FROM node:16

RUN apt-get update
# 降级安装 openssh-client
# RUN apt-get install -y --allow-downgrades openssh-client=1:7.2p2-4ubuntu2.10
RUN apt-get install -y openssh-server
RUN apt-get install -y net-tools
RUN apt-get install -y vim
RUN mkdir -p /var/run/sshd
RUN mkdir -p /root/.ssh/

#  修改root密码，便于远程登录
RUN echo root:123123 | chpasswd
#  将key生成在指定文件内
RUN ssh-keygen -q -t rsa -b 2048  -f /etc/ssh/ssh_host_rsa_key -P '' -N '' -y
#  配置ssh可以使用root登陆
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
# RUN sed 's/session\s*required\s*pam_loginuid.so/session optional pam_loginuid.so/g' -i /etc/pam.d/sshd

RUN mkdir -p /home/news/crawl

COPY . /home/news/crawl

WORKDIR /home/news/crawl

RUN mkdir -p /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb

RUN mv vscode-server-linux-x64.tar.gz /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb

RUN mv extensions /root/.vscode-server

WORKDIR /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb

RUN tar -zxvf vscode-server-linux-x64.tar.gz --strip-components 1

WORKDIR /home/news/crawl

RUN npm config set registry https://registry.npmmirror.com/

RUN npm install pm2 -g

RUN yarn

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]

# netstat -apn | grep ssh