export const STORAGE_KEY = {
  PLUGIN_PROPS: '@0x1461A0::accordion::STORAGE_PLUGIN_PROPS_KEY',
}

export const MESSAGE_TYPE = '@0x1461A0::PLUGIN_CONFIG_SYNC'

export const PLUGIN_CONFIG = '@0x1461A0::CUSTOMIZE_CONFIG_KEY'

export const MORE_MENU_ID = '@0x1461A0::PORTAL_ACCORDION::MENU_ITEM_MORE_ID'