export * from './storage_key'

export const PORTAL_HEADER_PLUGIN = '@0x1461A0::PORTAL_HEADER_PLUGIN::PLUGIN_CONFIG'

export const PORTAL_ACCORDION_PLUGIN = '@0x1461A0::PORTAL_ACCORDION_PLUGIN::PLUGIN_CONFIG'
