import '@/utils/runtime'

export const STORAGE_KEY = {
  DEFAULT_THEME: '@0x1461A0::STORAGE_DEFAULT_THEME_KEY',
  PLUGIN_PROPS: '@0x1461A0::STORAGE_PLUGIN_PROPS_KEY',
}

export const MESSAGE_TYPE = '@0x1461A0::PLUGIN_CONFIG_SYNC'

export const PLUGIN_CONFIG = '@0x1461A0::CUSTOMIZE_CONFIG_KEY'
